from uuid import UUID

from pydantic import BaseModel, Field


class BotResponse(BaseModel):
    uuid: UUID = Field(..., description="UUID of the bot")
    integration_uuid: UUID = Field(
        ..., description="Integration UUID related to that bot"
    )
    bot_token: str = Field(..., description="Bot token from Telegram API")
    api_key: UUID = Field(..., description="API key for our backend api")
    api_secret: str = Field(
        ...,
        description="API secret for our backend api. We are also using it as telegram webhook secret",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "uuid": "123e4567-e89b-12d3-a456-426614174000",
                "integration_uuid": "123e4567-e89b-12d3-a456-426614174000",
                "bot_token": "7516569554:AAFj-G7jpoBuj2UK5wBB7xEQxBuRVAPQCrU",
                "api_key": "123e4567-e89b-12d3-a456-426614174000",
                "api_secret": "qwerty123456",
            }
        }
    }


class BotCreatedResponse(BaseModel):
    uuid: UUID = Field(..., description="UUID of the bot")
    bot_user_name: str = Field(..., description="Bot user name")
    bot_title: str = Field(..., description="Bot title")


class NewBotRequest(BaseModel):
    uuid: UUID = Field(
        None,
        description="We will get UUID generated by backend api to make it simple. So UUID of the bot are same in both databases",
    )
    integration_uuid: UUID = Field(
        ..., description="Integration UUID related to that bot"
    )
    bot_token: str = Field(..., description="Bot token from Telegram API")
    api_key: UUID = Field(..., description="API key for our backend api")
    api_secret: str = Field(
        ...,
        description="API secret for our backend api. We are also using it as telegram webhook secret",
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "integration_uuid": "123e4567-e89b-12d3-a456-426614174000",
                "bot_token": "7516569554:AAFj-G7jpoBuj2UK5wBB7xEQxBuRVAPQCrU",
                "api_key": "123e4567-e89b-12d3-a456-426614174000",
                "api_secret": "qwerty123456",
            }
        }
    }
